name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build
      env:
        CI: true
    - name: deploy file to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: 'root'
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        rm: true
        source: './build/'
        target: '/www/webstack.maxmeng.top'
